<?php
/**
 * @author        Toni Uebernickel <toni@uebernickel.info>
 * @link          http://toni.uebernickel.info/
 *
 * @package       wspNopastePlugin
 * @subpackage    forms
 * @version       $Id$
 * @link          $HeadURL$
 */

/**
 * wspNopasteEntry administration form
 */
class wspNopasteEntryAdminForm extends BasewspNopasteEntryForm
{
  /**
   * add sfPropelActAsSluggableBehaviorPlugin and sfEasySyntaxHighlighter
   * removes created_by and slug from required widgets
   *
   * @return void
   */
  public function setup()
  {
    parent::setup();

    // geshi language
    $this->setWidget('language', new sfEasySyntaxHighlighterWidgetLanguageChoice(array('default' => 'text')));
    $this->setValidator('language', new sfEasySyntaxHighlighterValidatorLanguageChoice());

    // slug is generated by sfPropelActAsSluggableBehaviorPlugin
    $this->setValidator('slug', new sfValidatorString(array('max_length' => 255, 'required' => false)));

    // creator
    $this->setWidget('created_by', new sfWidgetFormPropelChoice(array('model' => 'sfGuardUser', 'add_empty' => true)));
    $this->setValidator('created_by', new sfValidatorPropelChoice(array('model' => 'sfGuardUser', 'required' => false)));

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);
  }
}
