<?php

/**
 * NopasteEntry form.
 *
 * @package    ##PROJECT_NAME##
 * @subpackage form
 * @author     ##AUTHOR_NAME##
 * @version    SVN: $Id: sfPropelFormTemplate.php 10377 2008-07-21 07:10:32Z dwhittle $
 */
class wspNopasteEntryAdminForm extends BasewspNopasteEntryForm
{
  /**
   * add sfPropelActAsSluggableBehaviorPlugin and sfEasySyntaxHighlighter
   *
   */
  public function setup()
  {
    parent::setup();

    // geshi language
    $this->setWidget('language', new sfEasySyntaxHighlighterWidgetLanguageChoice(array('default' => 'text')));
    $this->setValidator('language', new sfEasySyntaxHighlighterValidatorLanguageChoice());

    // slug is generated by sfPropelActAsSluggableBehaviorPlugin
    $this->setValidator('slug', new sfValidatorString(array('max_length' => 255, 'required' => false)));

    // creator
    $this->setWidget('created_by', new sfWidgetFormPropelChoice(array('model' => 'sfGuardUser', 'add_empty' => true)));
    $this->setValidator('created_by', new sfValidatorPropelChoice(array('model' => 'sfGuardUser', 'required' => false)));

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);
  }
}
