<?php


/**
 * This class adds structure of 'nopaste_entries' table to 'wsp-nopaste' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Jun 20 21:49:31 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.wspNopastePlugin.lib.model.map
 */
class wspNopasteEntryMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.wspNopastePlugin.lib.model.map.wspNopasteEntryMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(wspNopasteEntryPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(wspNopasteEntryPeer::TABLE_NAME);
		$tMap->setPhpName('wspNopasteEntry');
		$tMap->setClassname('wspNopasteEntry');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('CREATED_BY', 'CreatedBy', 'INTEGER', true, null);

		$tMap->addColumn('PASSWORD', 'Password', 'VARCHAR', false, 255);

		$tMap->addColumn('LANGUAGE', 'Language', 'VARCHAR', false, 10);

		$tMap->addColumn('TITLE', 'Title', 'VARCHAR', false, 120);

		$tMap->addColumn('SLUG', 'Slug', 'VARCHAR', true, 255);

		$tMap->addColumn('BODY', 'Body', 'LONGVARCHAR', false, null);

	} // doBuild()

} // wspNopasteEntryMapBuilder
