# @author        Toni Uebernickel <toni@uebernickel.info>
# @link          http://toni.uebernickel.info/
#
# @package       wspNopastePlugin
# @subpackage    config
# @version       $Id$
# @link          $HeadURL$

default:
  stylesheets:    [/wspNopastePlugin/css/vendor/sfPropelPlugin/global.css, /wspNopastePlugin/css/nopaste.css]