# @author        Toni Uebernickel <toni@uebernickel.info>
# @link          http://toni.uebernickel.info/
#
# @package       wspNopastePlugin
# @subpackage    config
# @version       $Id$
# @link          $HeadURL$

all:
  enabled: on
  with_layout: false
  contextual: true
  lifetime: 600